import * as cdk from 'aws-cdk-lib/core';
import { Construct } from 'constructs';
import * as s3 from 'aws-cdk-lib/aws-s3';

/**
 * StorageConstruct
 * 
 * Architectural Decision: Encapsulates S3 storage resources following ADR-005.
 * This construct manages the S3 bucket for image uploads, isolating all storage
 * configuration details from the main stack. This follows the Single Responsibility
 * Principle and makes the storage layer independently testable and reusable.
 * 
 * The construct exposes the bucket as a public property, allowing other constructs
 * to reference it for IAM permissions, event notifications, or presigned URL generation.
 */
export class StorageConstruct extends Construct {
  /**
   * Public property to expose the S3 upload bucket.
   * This enables other constructs to reference the bucket for:
   * - Generating presigned URLs
   * - Setting up S3 event notifications
   * - Granting IAM permissions to Lambda functions
   */
  public readonly uploadBucket: s3.Bucket;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    /**
     * S3 Bucket for image uploads.
     * Architectural Decision: This bucket is the entry point for the event-driven
     * architecture. Users upload images directly to S3 (via presigned URLs from
     * API Gateway), which then triggers Lambda processing via S3 event notifications.
     * 
     * Key Design Choices:
     * - S3_MANAGED encryption: AWS-managed keys for data at rest encryption without
     *   additional KMS costs. This is sufficient for MVP and provides automatic
     *   key rotation and compliance with many security standards.
     * - CORS: Allows browser-based uploads directly to S3, offloading traffic from
     *   the backend and reducing Lambda invocations (cost optimization).
     * - removalPolicy.DESTROY: Enables full cleanup during development. This MUST
     *   be changed to RETAIN for production to prevent accidental data loss.
     * - autoDeleteObjects: Works with removalPolicy.DESTROY to delete all objects
     *   when the stack is destroyed. This prevents "bucket not empty" errors during
     *   `cdk destroy` in development environments.
     * 
     * Security Consideration: Direct browser uploads are secured through presigned
     * URLs generated by the Auth Lambda, which enforces authentication and limits
     * file size/type. The bucket itself has no public access.
     */
    this.uploadBucket = new s3.Bucket(this, 'Bucket', {
      encryption: s3.BucketEncryption.S3_MANAGED,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
      cors: [
        {
          /**
           * CORS Configuration for browser-based uploads.
           * Architectural Decision: Allow PUT for uploads and GET for downloads.
           * AllowedOrigins is set to ['*'] for MVP to simplify development across
           * different environments (localhost, DevContainer, Cloud9, etc.).
           * 
           * Production TODO: Replace with specific allowed origins:
           * - CloudFront distribution URL
           * - Custom domain (if configured)
           * This prevents CSRF attacks and unauthorized access from malicious sites.
           * 
           * AllowedHeaders ['*'] permits any header, which is necessary for presigned
           * URL uploads that include authorization headers and content-type.
           */
          allowedMethods: [
            s3.HttpMethods.GET,
            s3.HttpMethods.PUT,
          ],
          allowedOrigins: ['*'], // TODO: Restrict to specific origins in production
          allowedHeaders: ['*'],
          /**
           * ExposeHeaders allows the browser to read these headers from the response.
           * ETag is useful for verifying upload integrity and implementing conditional
           * requests in the frontend (e.g., "only download if changed").
           */
          exposedHeaders: ['ETag'],
          /**
           * maxAge: How long (in seconds) the browser can cache the CORS preflight
           * response. 3000 seconds = 50 minutes. This reduces the number of OPTIONS
           * requests, improving performance and reducing S3 request costs.
           */
          maxAge: 3000,
        },
      ],
      /**
       * Block all public access by default.
       * Even though CORS is enabled, the bucket remains private and requires
       * presigned URLs for access. This is a defense-in-depth measure.
       */
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      /**
       * Versioning is disabled for MVP to reduce storage costs.
       * Production consideration: Enable versioning to:
       * - Protect against accidental deletions
       * - Comply with audit/compliance requirements
       * - Enable rollback capabilities
       */
      versioned: false,
    });
  }
}
